# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\STUDYQT\uiFiles\pageOne.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(186, 93)
        MainWindow.setStyleSheet("QWidget{\n"
"    background: rgb(57, 57, 57);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background: rgb(88, 94, 211);\n"
"    border: 2px solid rgb(0, 198, 216);\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background:rgb(0, 8, 129);\n"
"    border: 2px solid rgb(12, 218, 211);\n"
"    border-radius: 10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_pageName = QtWidgets.QLabel(self.centralwidget)
        self.lbl_pageName.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.lbl_pageName.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_pageName.setObjectName("lbl_pageName")
        self.btn_next = QtWidgets.QPushButton(self.centralwidget)
        self.btn_next.setGeometry(QtCore.QRect(100, 60, 75, 23))
        self.btn_next.setObjectName("btn_next")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_pageName.setText(_translate("MainWindow", "PG ONE"))
        self.btn_next.setText(_translate("MainWindow", "NEXT"))
