# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\STUDYQT\NEW_APP\maxVid.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(338, 260)
        MainWindow.setMinimumSize(QtCore.QSize(338, 260))
        MainWindow.setMaximumSize(QtCore.QSize(338, 260))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\STUDYQT\\NEW_APP\\res/mainIcon-480.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget{\n"
"    background: rgb(77, 77, 77);\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background: rgb(230, 230, 230);\n"
"    border: solid;\n"
"    border-radius: 8px;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background:rgb(216, 216, 216);\n"
"    border: solid;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background: rgb(230, 230, 230);\n"
"    color: black;\n"
"    border: solid;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QFrame {\n"
"    background: rgb(230, 230, 230);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_temp = QtWidgets.QLabel(self.centralwidget)
        self.lbl_temp.setGeometry(QtCore.QRect(190, 110, 130, 66))
        self.lbl_temp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_temp.setObjectName("lbl_temp")
        self.le_city = QtWidgets.QLineEdit(self.centralwidget)
        self.le_city.setGeometry(QtCore.QRect(20, 170, 101, 28))
        self.le_city.setObjectName("le_city")
        self.btn_slim = QtWidgets.QPushButton(self.centralwidget)
        self.btn_slim.setGeometry(QtCore.QRect(20, 220, 301, 31))
        self.btn_slim.setObjectName("btn_slim")
        self.lbl_weather = QtWidgets.QLabel(self.centralwidget)
        self.lbl_weather.setGeometry(QtCore.QRect(140, 20, 180, 55))
        self.lbl_weather.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_weather.setObjectName("lbl_weather")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 341, 211))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbl_icon_2 = QtWidgets.QLabel(self.frame)
        self.lbl_icon_2.setGeometry(QtCore.QRect(20, 20, 61, 61))
        self.lbl_icon_2.setText("")
        self.lbl_icon_2.setPixmap(QtGui.QPixmap("D:\\STUDYQT\\NEW_APP\\res/sunny-500.png"))
        self.lbl_icon_2.setScaledContents(True)
        self.lbl_icon_2.setObjectName("lbl_icon_2")
        self.frame.raise_()
        self.le_city.raise_()
        self.btn_slim.raise_()
        self.lbl_weather.raise_()
        self.lbl_temp.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_temp.setText(_translate("MainWindow", "temp"))
        self.le_city.setPlaceholderText(_translate("MainWindow", "Magadan"))
        self.btn_slim.setText(_translate("MainWindow", "Свернуть"))
        self.lbl_weather.setText(_translate("MainWindow", "Weather"))
