# Form implementation generated from reading ui file 'minVid.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(338, 150)
        MainWindow.setMinimumSize(QtCore.QSize(338, 150))
        MainWindow.setMaximumSize(QtCore.QSize(338, 150))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/mainIcon-480.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget{\n"
"    background: rgb(77, 77, 77);\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background: rgb(230, 230, 230);\n"
"    border: solid;\n"
"    border-radius: 8px;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background:rgb(216, 216, 216);\n"
"    border: solid;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: black;\n"
"    border: solid;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QFrame {\n"
"    background: rgb(230, 230, 230);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_max = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_max.setGeometry(QtCore.QRect(20, 110, 301, 31))
        self.btn_max.setObjectName("btn_max")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 341, 101))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.lbl_temp_2 = QtWidgets.QLabel(parent=self.frame)
        self.lbl_temp_2.setGeometry(QtCore.QRect(200, 20, 130, 66))
        self.lbl_temp_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_temp_2.setObjectName("lbl_temp_2")
        self.lbl_icon = QtWidgets.QLabel(parent=self.frame)
        self.lbl_icon.setGeometry(QtCore.QRect(20, 20, 61, 61))
        self.lbl_icon.setText("")
        self.lbl_icon.setPixmap(QtGui.QPixmap("res/sunny-500.png"))
        self.lbl_icon.setScaledContents(True)
        self.lbl_icon.setObjectName("lbl_icon")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_max.setText(_translate("MainWindow", "Развернуть"))
        self.lbl_temp_2.setText(_translate("MainWindow", "temp"))
