# Form implementation generated from reading ui file 'MainWin.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(451, 329)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(451, 329))
        MainWindow.setMaximumSize(QtCore.QSize(451, 329))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    color: #F6F6F6;\n"
"    background-color: #6B6B6B;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #F6F6F6;\n"
"    background-color: #7C7C7C;\n"
"    border: 1px solid #535EDF;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QTextEdit{\n"
"    color: #F6F6F6;\n"
"    background-color: #7C7C7C;\n"
"    border: 1px solid #2C65A2;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: black;\n"
"    background-color: #4487CF;\n"
"    border: 1px solid #2C65A2;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: black;\n"
"    background-color: #4C9CF2;\n"
"    border: 1px solid #2C65A2;\n"
"    border-radius: 10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.te_userEnter = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.te_userEnter.setGeometry(QtCore.QRect(10, 270, 341, 51))
        self.te_userEnter.setObjectName("te_userEnter")
        self.le_gptAnswer = QtWidgets.QLabel(parent=self.centralwidget)
        self.le_gptAnswer.setGeometry(QtCore.QRect(10, 10, 431, 251))
        self.le_gptAnswer.setObjectName("le_gptAnswer")
        self.btn_getAnswer = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_getAnswer.setGeometry(QtCore.QRect(360, 270, 81, 51))
        self.btn_getAnswer.setObjectName("btn_getAnswer")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.le_gptAnswer.setText(_translate("MainWindow", "TextLabel"))
        self.btn_getAnswer.setText(_translate("MainWindow", "Спросить!"))
