# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\а\Desktop\setings.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(525, 232)
        MainWindow.setStyleSheet("QWidget{\n"
"    background: rgb(57, 57, 57);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background: rgb(88, 94, 211);\n"
"    border: 2px solid rgb(0, 198, 216);\n"
"    border-radius: 15px;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background:rgb(0, 8, 129);\n"
"    border: 2px solid rgb(12, 218, 211);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background: rgb(88, 94, 211);\n"
"    border: 2px solid rgb(0, 198, 216);\n"
"    border-radius: 5px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_name = QtWidgets.QLabel(self.centralwidget)
        self.lbl_name.setGeometry(QtCore.QRect(10, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.lbl_name.setFont(font)
        self.lbl_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_name.setObjectName("lbl_name")
        self.lbl_IDEway = QtWidgets.QLabel(self.centralwidget)
        self.lbl_IDEway.setGeometry(QtCore.QRect(20, 50, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Yandex-UI-Icons-Private")
        self.lbl_IDEway.setFont(font)
        self.lbl_IDEway.setObjectName("lbl_IDEway")
        self.le_IDEway = QtWidgets.QLineEdit(self.centralwidget)
        self.le_IDEway.setGeometry(QtCore.QRect(20, 80, 361, 21))
        self.le_IDEway.setObjectName("le_IDEway")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(390, 190, 120, 30))
        self.btn_save.setObjectName("btn_save")
        self.lbl_browserWay = QtWidgets.QLabel(self.centralwidget)
        self.lbl_browserWay.setGeometry(QtCore.QRect(20, 120, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Yandex-UI-Icons-Private")
        self.lbl_browserWay.setFont(font)
        self.lbl_browserWay.setObjectName("lbl_browserWay")
        self.le_browserWay = QtWidgets.QLineEdit(self.centralwidget)
        self.le_browserWay.setGeometry(QtCore.QRect(20, 150, 361, 21))
        self.le_browserWay.setObjectName("le_browserWay")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_name.setText(_translate("MainWindow", "Настройки"))
        self.lbl_IDEway.setText(_translate("MainWindow", "путь к IDE"))
        self.btn_save.setText(_translate("MainWindow", "СТАРТ!"))
        self.lbl_browserWay.setText(_translate("MainWindow", "путь к браузеру"))
