# Form implementation generated from reading ui file 'win.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(824, 463)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background: rgb(77, 77, 77);\n"
"    color: white;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    background: rgb(230, 230, 230);\n"
"    border: solid;\n"
"    border-radius: 8px;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background:rgb(216, 216, 216);\n"
"    border: solid;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"\n"
"QLineEdit {\n"
"    color: black;\n"
"    border: solid;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QDateEdit {\n"
"    color: black;\n"
"    border: solid;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_view = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_view.setGeometry(QtCore.QRect(130, 10, 681, 441))
        self.lbl_view.setObjectName("lbl_view")
        self.le_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.le_name.setGeometry(QtCore.QRect(10, 40, 111, 20))
        self.le_name.setObjectName("le_name")
        self.de_date = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.de_date.setGeometry(QtCore.QRect(10, 100, 111, 22))
        self.de_date.setObjectName("de_date")
        self.btn_commit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_commit.setGeometry(QtCore.QRect(10, 422, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_commit.setFont(font)
        self.btn_commit.setObjectName("btn_commit")
        self.lbl_date = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_date.setGeometry(QtCore.QRect(10, 70, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lbl_date.setFont(font)
        self.lbl_date.setObjectName("lbl_date")
        self.lbl_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_name.setGeometry(QtCore.QRect(10, 10, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lbl_name.setFont(font)
        self.lbl_name.setObjectName("lbl_name")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_view.setText(_translate("MainWindow", "TextLabel"))
        self.btn_commit.setText(_translate("MainWindow", "добавить"))
        self.lbl_date.setText(_translate("MainWindow", "дата:"))
        self.lbl_name.setText(_translate("MainWindow", "имя:"))
